### PR TITLE
feat: query specific education by `id`

### LINKED ISSUE #16: Implement API route to return a specific Education
On the `/resume/education` route, you should

- [ ] Return a specific Education when a GET request is made with an index as an input. The Education should be in a JSON format.

### PR DESCRIPTION
**Pull request by winstxnhdw**
## Summary

Returns a specific `Education` when a GET request is made with an index as an input.

Closes #16

### CODE REVIEW

**Review by Pradyuman7 — APPROVED** [review]
LGTM 👍 

Can you resolve the conflict, I'll merge then

**Comment by winstxnhdw** [comment]
Done

**Comment by Pradyuman7** [comment]
Woops, one more conflict, can you please fix it?

**Comment by winstxnhdw** [comment]
Sure, done

**Pull request merged**
