### PR TITLE
Get for resume/skill

### PR DESCRIPTION
**Pull request by IvanKolchanov**
Added the Get functionality for the resume/skill route
Closes issues:
https://github.com/MLH-Fellowship/orientation-project-python-24.SUM.A/issues/13

### CODE REVIEW

**Comment by IvanKolchanov** [comment]
@Pradyuman7

**Review by Pradyuman7 — COMMENTED** [review]
Can we also have some tests for this unless there's a different issue for that. Also, I totally get that these two issues are related but it'd be better to do each in a different PR so it's easier to track which issues are resolved by which PRs

**Comment by IvanKolchanov** [comment]
Okey, I can write tests for that and I can separate the issues into 2 PR's! I just have been having some issues with pytest, but I should be able to figure it out. Thanks for the feedback!

**Comment by IvanKolchanov** [comment]
@Pradyuman7 fixed the issues you poited out!

**Review by Pradyuman7 — APPROVED** [review]
LGTM 💯
We can merge after we resolve the conflicts

**Comment by IvanKolchanov** [comment]
@Pradyuman7 resolved the conflict, ready to merge!

**Comment by Pradyuman7** [comment]
> @Pradyuman7 resolved the conflict, ready to merge!

Ah, we have one more since I merged a PR, I'll merge this one next, could you please also take care of this

**Comment by IvanKolchanov** [comment]
> > @Pradyuman7 resolved the conflict, ready to merge!
> 
> Ah, we have one more since I merged a PR, I'll merge this one next, could you please also take care of this

Should be resolved now! 👍

**Pull request merged**
